// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To regenerate this file, run `flutterfire configure` from the project root.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB-kTKZbEbLtBJnelsKYc8soYoKhs7Av4',
    appId: '1:654625579884:android:a5218eb5bebfa517230949',
    messagingSenderId: '654625579884',
    projectId: 'comtammatu-d9adb',
    storageBucket: 'comtammatu-d9adb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqaluVntIMsI2QDWt2oK4B57Sm06eLyHc',
    appId: '1:654625579884:ios:132b83cccdd40746230949',
    messagingSenderId: '654625579884',
    projectId: 'comtammatu-d9adb',
    storageBucket: 'comtammatu-d9adb.firebasestorage.app',
    iosBundleId: 'com.comtammatu.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB-kTKZbEbLtBJnelsKYc8soYoKhs7Av4',
    appId: '1:654625579884:web:5f1d9da74d275679230949',
    messagingSenderId: '654625579884',
    projectId: 'comtammatu-d9adb',
    storageBucket: 'comtammatu-d9adb.firebasestorage.app',
  );
}
